/** Contenu i18n de la landing (HomeView). Separe du composant pour centraliser
 *  les textes FR/EN et faciliter la relecture / traduction. */

export const homeCopy = {
  fr: {
    heroTitle: 'Prépare-toi aux\ncompétences de demain.',
    heroSub: 'Etudesk aide chaque talent à découvrir, apprendre et valoriser les compétences numériques qui ouvrent des opportunités locales et internationales. Un tuteur IA pour apprendre, un guide carrière IA pour avancer. Dans ta poche, à ton rythme.',
    heroExplore: 'Voir le référentiel',
    trust: '3 000 000+ formés  ·  53 pays  ·  depuis 2016',

    whyEyebrow: 'Pourquoi maintenant',
    whyTitle: 'Pourquoi les compétences du numérique ?',
    whySub: 'Un seul socle de compétences ouvre les portes du marché mondial du travail - et l\'IA n\'a jamais rendu leur apprentissage aussi rapide.',
    why1t: 'Transversales', why1d: 'Des compétences qui s\'appliquent à tous les métiers, dans tous les secteurs.',
    why2t: 'Un marché mondial', why2d: 'Accède à un marché d\'opportunités à l\'échelle de la planète.',
    why3t: 'Parmi les mieux payés', why3d: 'Les compétences digitales figurent parmi les emplois les mieux rémunérés.',
    why4t: 'Accessibles à tous', why4d: 'Juste un smartphone et une connexion internet suffisent pour démarrer.',

    loopTitle: 'Apprendre et décrocher un emploi ne devraient pas être deux mondes',
    loopLead: 'D\'un côté les cours et les tuteurs. De l\'autre les offres et le matching. Etudesk réunit les deux sur une seule colonne vertébrale : tes compétences. Une compétence apprise devient aussitôt un critère d\'opportunité.',
    loopSteps: ['Apprends', 'Maîtrise', 'Décroche'],
    learnTitle: 'Apprendre',
    learnDesc: 'Plans d\'apprentissage, explications, pratique vraiment interactive. Ton tuteur ne donne pas la réponse : il te guide.',
    learnList: [
      { t: 'Quiz & flashcards', d: 'Générés automatiquement depuis n\'importe quel cours pour ancrer durablement ce que tu apprends.' },
      { t: 'Exercices & résolution pas à pas', d: 'Le tuteur décompose chaque problème étape par étape, jusqu\'à ce que tu comprennes vraiment.' },
      { t: 'Playground de code (JS / Python)', d: 'Écris, exécute et fais corriger ton code en direct, sans jamais quitter l\'app.' },
      { t: 'Multimodal : diagrammes, audio, vidéos', d: 'Chaque notion t\'est expliquée dans le format qui te parle le plus.' },
    ],
    advanceTitle: 'Avancer',
    advanceDesc: 'Tes compétences reliées à de vraies opportunités, un CV généré, des entretiens préparés.',
    advanceList: [
      { t: 'Opportunités adaptées à ton profil', d: 'L\'IA scanne le marché et te propose emplois, stages et missions qui matchent réellement tes compétences.' },
      { t: 'CV généré sur mesure', d: 'Un CV optimisé pour chaque opportunité, prêt en un clic.' },
      { t: 'Préparation d\'entretiens', d: 'Simulations d\'entretien et feedback personnalisé pour arriver prêt le jour J.' },
      { t: 'Communautés & espaces', d: 'Rejoins les bons réseaux et événements pour accélérer ta carrière.' },
    ],

    agentsEyebrow: 'Deux agents, une boucle',
    agent1Eyebrow: 'Tuteur IA', agent2Eyebrow: 'Guide carrière IA',
    learnBadge: 'Guidé, jamais la réponse', advanceBadge: 'CV généré',

    refEyebrow: 'Le référentiel',
    refTitle: 'Pas un catalogue figé. Un écosystème vivant.',
    refDesc: 'Notre référentiel propriétaire agrège les meilleurs cadres mondiaux de compétences numériques et les signaux réels du marché de l\'emploi. Chaque compétence sait ce qui vient avant, à côté et après : l\'app te donne toujours le prochain pas.',
    refSkills: 'compétences', refFamilies: 'familles', refRelations: 'liens typés',
    refPoint1T: 'Des savoirs qui durent',
    refPoint1B: '60% des fondations',
    refPoint1D: ' sont des concepts durables, pas des outils périssables. Tu apprends ce qui reste.',
    refPoint2T: 'Des parcours, pas une liste',
    refPoint2D: 'Les compétences s\'enchaînent en parcours d\'apprentissage allant jusqu\'à 13 niveaux. De zéro à la pointe de l\'IA, étape par étape.',
    refCta: 'Voir le référentiel',

    featsTitle: 'Tout ce qu\'il te faut, au même endroit',
    f1t: 'Découvrir l\'écosystème', f1d: 'Opportunités (emplois, stages, missions, formations), communautés et espaces. Tri par pertinence, proximité, recence.',
    f2t: 'Tes compétences', f2d: 'Déclare-les depuis le référentiel, suis ta progression, niveaux débutant à maître validés par la pratique.',
    f3t: 'Ton profil & ta carrière', f3d: 'Profil, documents (CV, certificats), candidatures, réservations, invitations.',
    f4t: 'Multimodal', f4d: 'Texte, voix (transcription), pièces jointes (PDF, images).',
    f5t: 'Multilingue', f5d: 'Plusieurs langues, à l\'écrit comme à la voix.',
    f6t: 'Onboarding express', f6d: 'Connexion email + code. Profil en quelques étapes, sans test d\'admission.',

    creditsT: 'Commence avec 30 crédits offerts',
    creditsD: 'Chaque requête IA coûte 1 crédit. Quiz, flashcards, diagrammes, recherche et candidatures restent gratuits. Recharge à ton rythme, sans abonnement.',
    creditsRows: [['Assistant Explorer', '1 crédit'], ['Assistant Study', '1 crédit'], ['Assistant Manager', '1 crédit'], ['Suggestions IA de formulaires', '1 crédit'], ['Génération de documents', '1 crédit'], ['Génération d’images', '1 crédit'], ['Quiz / Flashcards / Diagrammes', 'Gratuit'], ['Recherche web / vidéo', 'Gratuit'], ['Postuler / Réserver / Adhérer', 'Gratuit']],

    histTitle: 'Notre histoire',
    histBody: [
      { t: 'Pendant dix ans, Etudesk a porté "', b: false },
      { t: 'l\'université des entreprises', b: true },
      { t: '" : donner à chacun les compétences qui changent une trajectoire. Aujourd\'hui, nous changeons d\'échelle. La même exigence de formation, désormais dans ta poche, augmentée par l\'IA et reliée à de vraies opportunités. Parce qu\'apprendre ne devrait jamais être un privilège : ', b: false },
      { t: 'juste un point de départ', b: true },
      { t: '.', b: false },
    ],
    stat1: 'personnes formées', stat2: 'organisations', stat3: 'pays', stat4: 'au service de l\'éducation',
    teamTitle: 'Les humains derrière l\'IA',

    ctaTitle: 'Prêt à prendre une longueur d\'avance ?',
    ctaSub: 'Télécharge Etudesk et commence avec 30 crédits offerts.',
  },
  en: {
    heroTitle: 'Get ready for\ntomorrow\'s skills.',
    heroSub: 'Etudesk helps every talent discover, learn and showcase the digital skills that open local and international opportunities. An AI tutor to learn, an AI career guide to advance. In your pocket, at your pace.',
    heroExplore: 'See the referential',
    trust: '3,000,000+ trained  ·  53 countries  ·  since 2016',

    whyEyebrow: 'Why now',
    whyTitle: 'Why digital skills?',
    whySub: 'One set of skills opens the doors to the global job market - and AI has never made them this fast to learn.',
    why1t: 'Cross-cutting', why1d: 'Skills that apply to every job, in every industry.',
    why2t: 'A global market', why2d: 'Tap into a worldwide market of opportunities.',
    why3t: 'Among the best paid', why3d: 'Digital skills rank among the highest-paid jobs.',
    why4t: 'Accessible to all', why4d: 'Just a smartphone and an internet connection to get started.',

    loopTitle: 'Learning and getting hired should not be two worlds',
    loopLead: 'On one side, courses and tutors. On the other, jobs and matching. Etudesk brings both onto one backbone: your skills. A skill you learn instantly becomes an opportunity criterion.',
    loopSteps: ['Learn', 'Master', 'Get hired'],
    learnTitle: 'Learn',
    learnDesc: 'Learning plans, explanations, genuinely interactive practice. Your tutor guides you instead of just giving answers.',
    learnList: [
      { t: 'Quizzes & flashcards', d: 'Auto-generated from any course to lock in what you learn for the long run.' },
      { t: 'Step-by-step solving', d: 'The tutor breaks down every problem one step at a time, until you truly get it.' },
      { t: 'Code playground (JS / Python)', d: 'Write, run and debug your code live, without ever leaving the app.' },
      { t: 'Multimodal: diagrams, audio, video', d: 'Every concept explained in the format that clicks for you.' },
    ],
    advanceTitle: 'Advance',
    advanceDesc: 'Your skills connected to real opportunities, a generated CV, prepped interviews.',
    advanceList: [
      { t: 'Opportunities matched to you', d: 'The AI scans the market and surfaces jobs, internships and gigs that truly fit your skills.' },
      { t: 'Tailored CV generation', d: 'A CV optimised for each opportunity, ready in one click.' },
      { t: 'Interview preparation', d: 'Mock interviews and personalised feedback so you show up ready.' },
      { t: 'Communities & spaces', d: 'Join the right networks and events to accelerate your career.' },
    ],

    agentsEyebrow: 'Two agents, one loop',
    agent1Eyebrow: 'AI Tutor', agent2Eyebrow: 'AI Career Guide',
    learnBadge: 'Guided, never spoon-fed', advanceBadge: 'CV generated',

    refEyebrow: 'The referential',
    refTitle: 'Not a frozen catalog. A living ecosystem.',
    refDesc: 'Our proprietary referential aggregates the world\'s leading digital skills frameworks and real job-market signals. Every skill knows what comes before, beside and after it: the app always gives you the next step.',
    refSkills: 'skills', refFamilies: 'families', refRelations: 'typed links',
    refPoint1T: 'Knowledge that lasts',
    refPoint1B: '60% of the foundations',
    refPoint1D: ' are durable concepts, not perishable tools. You learn what stays.',
    refPoint2T: 'Paths, not a list',
    refPoint2D: 'Skills chain into learning paths up to 13 levels deep. From zero to the cutting edge of AI, step by step.',
    refCta: 'See the referential',

    featsTitle: 'Everything you need, in one place',
    f1t: 'Discover the ecosystem', f1d: 'Opportunities (jobs, internships, gigs, trainings), communities and spaces. Sort by relevance, proximity, recency.',
    f2t: 'Your skills', f2d: 'Declare them from the referential, track progress, beginner to master levels earned by practice.',
    f3t: 'Your profile & career', f3d: 'Profile, documents (CV, certificates), applications, bookings, invitations.',
    f4t: 'Multimodal', f4d: 'Text, voice (transcription), attachments (PDF, images).',
    f5t: 'Multilingual', f5d: 'Several languages, written and voice.',
    f6t: 'Express onboarding', f6d: 'Email login + code. Profile in a few steps, no admission test.',

    creditsT: 'Start with 30 free credits',
    creditsD: 'Each AI request costs 1 credit. Quizzes, flashcards, diagrams, search and applications remain free. Top up at your pace, no subscription.',
    creditsRows: [['Assistant Explorer', '1 credit'], ['Assistant Study', '1 credit'], ['Assistant Manager', '1 credit'], ['AI form suggestions', '1 credit'], ['Document generation', '1 credit'], ['Image generation', '1 credit'], ['Quiz / Flashcards / Diagrams', 'Free'], ['Web / video search', 'Free'], ['Apply / Book / Join', 'Free']],

    histTitle: 'Our story',
    histBody: [
      { t: 'For ten years, Etudesk carried "', b: false },
      { t: 'the university of companies', b: true },
      { t: '": giving everyone the skills that change a trajectory. Today, we are scaling up. The same standard of training, now in your pocket, augmented by AI and connected directly to real opportunities. Because learning should never be a privilege - only ', b: false },
      { t: 'a starting point', b: true },
      { t: '.', b: false },
    ],
    stat1: 'people trained', stat2: 'organisations', stat3: 'countries', stat4: 'serving education',
    teamTitle: 'The humans behind the AI',

    ctaTitle: 'Ready to get ahead?',
    ctaSub: 'Download Etudesk and start with 30 free credits.',
  },
};
