/** Contenu i18n de la landing (HomeView). Separe du composant pour centraliser
 *  les textes FR/EN et faciliter la relecture / traduction. */

export const homeCopy = {
  fr: {
    heroTitle: 'Les compétences numériques\nqui font avancer votre travail.',
    heroSub: 'Découvrez quoi apprendre, pratiquez avec un tuteur IA et transformez vos progrès en résultats concrets : mieux travailler, évoluer, décrocher une opportunité ou faire grandir un projet.',
    heroExplore: 'Voir le référentiel',
    trust: '3 000 000+ formés  ·  53 pays  ·  depuis 2016',

    whyEyebrow: 'Pourquoi maintenant',
    whyTitle: 'Pourquoi les compétences du numérique ?',
    whySub: 'Les compétences numériques ne sont pas réservées aux métiers de la tech : elles augmentent la qualité, la vitesse et l\'autonomie dans presque tous les rôles.',
    why1t: 'Utiles dans tous les métiers', why1d: 'IA, données, communication et outils collaboratifs : un socle qui s\'applique à votre contexte.',
    why2t: 'Orientées résultat', why2d: 'Apprenez pour produire un livrable, résoudre un problème ou préparer une prochaine étape de carrière.',
    why3t: 'Apprendre par la pratique', why3d: 'Passez de la découverte à la maîtrise avec des exercices, projets et retours immédiats.',
    why4t: 'À votre rythme', why4d: 'Des parcours accessibles sur mobile, adaptés au temps dont vous disposez et à votre niveau de départ.',

    loopTitle: 'Une compétence utile doit mener à une action concrète',
    loopLead: 'Etudesk relie ce que vous apprenez à ce que vous voulez accomplir. Une compétence pratiquée peut améliorer votre travail, enrichir votre profil et vous rapprocher d\'une opportunité.',
    loopSteps: ['Apprends', 'Maîtrise', 'Décroche'],
    learnTitle: 'Apprendre',
    learnDesc: 'Plans d\'apprentissage, explications, pratique vraiment interactive. Ton tuteur ne donne pas la réponse : il te guide.',
    learnList: [
      { t: 'Quiz & flashcards', d: 'Générés automatiquement depuis n\'importe quel cours pour ancrer durablement ce que tu apprends.' },
      { t: 'Exercices & résolution pas à pas', d: 'Le tuteur décompose chaque problème étape par étape, jusqu\'à ce que tu comprennes vraiment.' },
      { t: 'Playground de code (JS / Python)', d: 'Écris, exécute et fais corriger ton code en direct, sans jamais quitter l\'app.' },
      { t: 'Multimodal : diagrammes, audio, vidéos', d: 'Chaque notion t\'est expliquée dans le format qui te parle le plus.' },
    ],
    advanceTitle: 'Avancer',
    advanceDesc: 'Vos compétences reliées à des opportunités, un profil plus clair et des prochaines actions concrètes.',
    advanceList: [
      { t: 'Opportunités adaptées à votre profil', d: 'Identifiez des emplois, missions, formations et communautés cohérents avec vos compétences et vos objectifs.' },
      { t: 'CV généré sur mesure', d: 'Un CV optimisé pour chaque opportunité, prêt en un clic.' },
      { t: 'Préparation d\'entretiens', d: 'Simulations d\'entretien et feedback personnalisé pour arriver prêt le jour J.' },
      { t: 'Communautés & espaces', d: 'Rejoins les bons réseaux et événements pour accélérer ta carrière.' },
    ],

    agentsEyebrow: 'Deux agents, une boucle',
    agent1Eyebrow: 'Tuteur IA', agent2Eyebrow: 'Guide carrière IA',
    learnBadge: 'Guidé, jamais la réponse', advanceBadge: 'CV généré',

    refEyebrow: 'Le référentiel',
    refTitle: 'Pas un catalogue figé. Un écosystème vivant.',
    refDesc: 'Notre référentiel propriétaire agrège les meilleurs cadres mondiaux de compétences numériques et les signaux réels du marché de l\'emploi. Chaque compétence sait ce qui vient avant, à côté et après : l\'app te donne toujours le prochain pas.',
    refSkills: 'compétences', refFamilies: 'familles', refRelations: 'liens typés',
    refPoint1T: 'Des savoirs qui durent',
    refPoint1B: '60% des fondations',
    refPoint1D: ' sont des concepts durables, pas des outils périssables. Tu apprends ce qui reste.',
    refPoint2T: 'Des parcours, pas une liste',
    refPoint2D: 'Les compétences s\'enchaînent en parcours d\'apprentissage allant jusqu\'à 13 niveaux. De zéro à la pointe de l\'IA, étape par étape.',
    refCta: 'Voir le référentiel',

    featsTitle: 'Tout ce qu\'il te faut, au même endroit',
    f1t: 'Découvrir votre prochain pas', f1d: 'Opportunités, formations, communautés et ressources sélectionnées selon votre objectif et vos compétences.',
    f2t: 'Tes compétences', f2d: 'Déclare-les depuis le référentiel, suis ta progression, niveaux débutant à maître validés par la pratique.',
    f3t: 'Ton profil & ta carrière', f3d: 'Profil, documents (CV, certificats), candidatures, réservations, invitations.',
    f4t: 'Multimodal', f4d: 'Texte, voix (transcription), pièces jointes (PDF, images).',
    f5t: 'Multilingue', f5d: 'Plusieurs langues, à l\'écrit comme à la voix.',
    f6t: 'Onboarding utile', f6d: 'En quelques étapes, choisissez votre objectif et vos secteurs pour commencer avec un parcours pertinent.',

    creditsT: 'Commence avec 30 crédits offerts',
    creditsD: 'Chaque requête IA coûte 1 crédit. Quiz, flashcards, diagrammes, recherche et candidatures restent gratuits. Recharge à ton rythme, sans abonnement.',
    creditsRows: [['Assistant Explorer', '1 crédit'], ['Assistant Study', '1 crédit'], ['Assistant Manager', '1 crédit'], ['Suggestions IA de formulaires', '1 crédit'], ['Génération de documents', '1 crédit'], ['Génération d’images', '1 crédit'], ['Quiz / Flashcards / Diagrammes', 'Gratuit'], ['Recherche web / vidéo', 'Gratuit'], ['Postuler / Réserver / Adhérer', 'Gratuit']],

    histTitle: 'Notre histoire',
    histBody: [
      { t: 'Pendant dix ans, Etudesk a porté "', b: false },
      { t: 'l\'université des entreprises', b: true },
      { t: '" : donner à chacun les compétences qui changent une trajectoire. Aujourd\'hui, nous changeons d\'échelle. La même exigence de formation, désormais dans ta poche, augmentée par l\'IA et reliée à de vraies opportunités. Parce qu\'apprendre ne devrait jamais être un privilège : ', b: false },
      { t: 'juste un point de départ', b: true },
      { t: '.', b: false },
    ],
    stat1: 'personnes formées', stat2: 'organisations', stat3: 'pays', stat4: 'au service de l\'éducation',
    teamTitle: 'Les humains derrière l\'IA',

    ctaTitle: 'Prêt à prendre une longueur d\'avance ?',
    ctaSub: 'Télécharge Etudesk et commence avec 30 crédits offerts.',
  },
  en: {
    heroTitle: 'Digital skills\nthat move your work forward.',
    heroSub: 'Discover what to learn, practise with an AI tutor, and turn progress into concrete outcomes: work better, grow your career, access opportunities, or build a project.',
    heroExplore: 'See the referential',
    trust: '3,000,000+ trained  ·  53 countries  ·  since 2016',

    whyEyebrow: 'Why now',
    whyTitle: 'Why digital skills?',
    whySub: 'Digital skills are not reserved for technology roles: they increase quality, speed and autonomy in almost every kind of work.',
    why1t: 'Useful in every role', why1d: 'AI, data, communication and collaborative tools form a foundation you can apply in your own context.',
    why2t: 'Outcome-led', why2d: 'Learn to produce a deliverable, solve a problem or prepare your next career step.',
    why3t: 'Practice to progress', why3d: 'Move from discovery to mastery with exercises, projects and immediate feedback.',
    why4t: 'At your own pace', why4d: 'Mobile-first paths suited to your available time and starting level.',

    loopTitle: 'A useful skill should lead to concrete action',
    loopLead: 'Etudesk connects what you learn to what you want to achieve. A skill you practise can improve your work, strengthen your profile and bring you closer to an opportunity.',
    loopSteps: ['Learn', 'Master', 'Get hired'],
    learnTitle: 'Learn',
    learnDesc: 'Learning plans, explanations, genuinely interactive practice. Your tutor guides you instead of just giving answers.',
    learnList: [
      { t: 'Quizzes & flashcards', d: 'Auto-generated from any course to lock in what you learn for the long run.' },
      { t: 'Step-by-step solving', d: 'The tutor breaks down every problem one step at a time, until you truly get it.' },
      { t: 'Code playground (JS / Python)', d: 'Write, run and debug your code live, without ever leaving the app.' },
      { t: 'Multimodal: diagrams, audio, video', d: 'Every concept explained in the format that clicks for you.' },
    ],
    advanceTitle: 'Advance',
    advanceDesc: 'Your skills connected to opportunities, a clearer profile and practical next actions.',
    advanceList: [
      { t: 'Opportunities matched to you', d: 'Find jobs, projects, training and communities that align with your skills and goals.' },
      { t: 'Tailored CV generation', d: 'A CV optimised for each opportunity, ready in one click.' },
      { t: 'Interview preparation', d: 'Mock interviews and personalised feedback so you show up ready.' },
      { t: 'Communities & spaces', d: 'Join the right networks and events to accelerate your career.' },
    ],

    agentsEyebrow: 'Two agents, one loop',
    agent1Eyebrow: 'AI Tutor', agent2Eyebrow: 'AI Career Guide',
    learnBadge: 'Guided, never spoon-fed', advanceBadge: 'CV generated',

    refEyebrow: 'The referential',
    refTitle: 'Not a frozen catalog. A living ecosystem.',
    refDesc: 'Our proprietary referential aggregates the world\'s leading digital skills frameworks and real job-market signals. Every skill knows what comes before, beside and after it: the app always gives you the next step.',
    refSkills: 'skills', refFamilies: 'families', refRelations: 'typed links',
    refPoint1T: 'Knowledge that lasts',
    refPoint1B: '60% of the foundations',
    refPoint1D: ' are durable concepts, not perishable tools. You learn what stays.',
    refPoint2T: 'Paths, not a list',
    refPoint2D: 'Skills chain into learning paths up to 13 levels deep. From zero to the cutting edge of AI, step by step.',
    refCta: 'See the referential',

    featsTitle: 'Everything you need, in one place',
    f1t: 'Discover your next step', f1d: 'Opportunities, learning paths, communities and resources selected around your goals and skills.',
    f2t: 'Your skills', f2d: 'Declare them from the referential, track progress, beginner to master levels earned by practice.',
    f3t: 'Your profile & career', f3d: 'Profile, documents (CV, certificates), applications, bookings, invitations.',
    f4t: 'Multimodal', f4d: 'Text, voice (transcription), attachments (PDF, images).',
    f5t: 'Multilingual', f5d: 'Several languages, written and voice.',
    f6t: 'Useful onboarding', f6d: 'Choose your goal and sectors in a few steps to begin with a relevant path.',

    creditsT: 'Start with 30 free credits',
    creditsD: 'Each AI request costs 1 credit. Quizzes, flashcards, diagrams, search and applications remain free. Top up at your pace, no subscription.',
    creditsRows: [['Assistant Explorer', '1 credit'], ['Assistant Study', '1 credit'], ['Assistant Manager', '1 credit'], ['AI form suggestions', '1 credit'], ['Document generation', '1 credit'], ['Image generation', '1 credit'], ['Quiz / Flashcards / Diagrams', 'Free'], ['Web / video search', 'Free'], ['Apply / Book / Join', 'Free']],

    histTitle: 'Our story',
    histBody: [
      { t: 'For ten years, Etudesk carried "', b: false },
      { t: 'the university of companies', b: true },
      { t: '": giving everyone the skills that change a trajectory. Today, we are scaling up. The same standard of training, now in your pocket, augmented by AI and connected directly to real opportunities. Because learning should never be a privilege - only ', b: false },
      { t: 'a starting point', b: true },
      { t: '.', b: false },
    ],
    stat1: 'people trained', stat2: 'organisations', stat3: 'countries', stat4: 'serving education',
    teamTitle: 'The humans behind the AI',

    ctaTitle: 'Ready to get ahead?',
    ctaSub: 'Download Etudesk and start with 30 free credits.',
  },
};
